### ISSUE TITLE
Licenciamento.

### ISSUE THREAD

**Issue by cpicanco** [eep-lab/eam_docs#2]
É recomendável licenciar o programa/projeto. Eu recomendo GPL3. Mas é necessário discutir.

**Comment by ofgalvao** [comment]
Prezado Carlos,
O que é GPL3?
Acredito que seja uma boa proposta, apenas sugiro que a autoria, se existe isso, deveria incluir os que trabalharam ao longo dos anos no EAM.

**Comment by cpicanco** [comment]
Caro Olavo,

Eu estive pensando sobre o assunto da autoria para fins de registro do software e concordo com você, ela deve incluir todos aqueles que trabalharam ao longo dos anos, seja escrevendo o código, seja orientando o trabalho dos escritores (programadores, desenvolvedores), seja trabalhando na documentação do software. Num primeiro momento, eu pensei que não seria tão difícil fazer uma lista com esses nomes. Mas quando pensei no contexto de São Carlos, ainda com o Drausio ativamente desenvolvendo (até aonde eu sei), eu considerei a terefa mais difícil. Até aonde eu me informei com a advogada da encubadora de empresas da UFPA, há também os autores na forma de pessoas jurídicas, como a UFPA e a UFSCar.

O licenciamento, entretanto, é diferente do registro formal propriamente dito junto ao [Instituto Nacional de Propriedade Intelectual](http://www.inpi.gov.br/portal/acessoainformacao/artigo/programa_de_computador_1351692237105). Hoje o Dionne está registrando dois softwares e ele talvez possa nos ajudar nessa tarefa do registro formal. As informações sobre o licenciamento irão constar nos registros do INPI. Perguntas norteadores em relação ao licenciamento:
- "O que queremos, quais os nossos interesses?"
- "Quais as licenças de outros projetos semelhantes?"
- "Quais conflitos de interesses devemos estar preparados para evitar?"

Com base nas respostas, acho que já seria possível optar por uma licença ou outra.

O GPL3 é uma licença conhecida como CopyLeft (em oposição ao Copyright), originada em um contexto de software livre que tem dentre um de seus objetivos o de evitar monopólios do códico fonte, isto é, evitar a privatização de trabalhos coletivos na forma de apropriações indevidas. Isso não impede, eventualmente, a venda de serviços associados ao software ou alguma outra forma de geração de recursos na medida em que os direitos e deveres assegurados pela licença (em relação ao código e não aos serviços) sejam respeitados.  

GPL3:

```
https://www.gnu.org/licenses/quick-guide-gplv3.html
http://en.wikipedia.org/wiki/GNU_General_Public_License
```

discussões em torno da licença:

```
http://stackoverflow.com/questions/11670368/gpl-copyright-notice-when-contributing-new-files
http://lucumr.pocoo.org/2009/2/12/are-you-sure-you-want-to-use-gpl/
```

Outra tipo de licença que tenho encontrado frequentemente é a Creative commons:

```
creativecommons.org/
```

Exemplos de projetos GPL3:
- [Pesquisa no Google: GPL3 site:github.com](https://www.google.com.br/search?q=GPL3+GPLv3+site:github.com&safe=off&biw=1280&bih=642&ei=xzExVYWoEYmGsAXXoYH4Cg&start=10&sa=N)

**Comment by ofgalvao** [comment]
Oi Rafael,

Obrigado por suas explicações.

Se entendi bem, temos a possibilidade de registrar o software no INPI.

Uma vez registrado, ainda resta a tarefa de Licenciamento. Correto?

Quanto à autoria, salvo melhor juízo, proponho como autores pessoas
físicas. O Drausio seria consultado para saber se ele aceita participar
como co-autor. Como criador ele pode discordar de dar co-autoria, mas
acredito que dificilmente ele faria isso.

Faça a lista de autores para eu entrar em contato com o Drausio já com uma
proposta.

Quanto ao licenciamento, faça sua proposta, a partir do que conheces das
duas opções e do EAM.

Me parece, com o conhecimento superficial que tenho, que a GPL3 seria
adequada.

Att

Olavo F. Galvão
Prof. Titular Psicol. Experimental, PPGNC, NTPC, UFPA
http://www.ufpa.br/eep/
The brain doesn't think, does nothing mental. The body in its integrity,
not only the brain, sustain the flux of consciousness without being
conscient. During life afferences and efferences make ways respectively
divergent and convergent. In a given instant t zero a set of afferences
demand cortices in different levels and areas. The cortices receive the
aferences, receive also lateral activation -intercortical- (t one) and
re-send the activation laterally and/or start eferences (t two).
Activations may be electrical or chemical, and can be excitatory,

## inibitory, modulatory. [to be continued]

O cérebro não pensa, não faz nada mental. O corpo como um todo, não o
cérebro apenas, sustenta o fluxo da consciência sem ser consciente. Ao
longo da vida, aferências e eferências formam caminhos respectivamente
divergentes e convergentes. Em um dado instante t zero um conjunto de
aferências demanda córtices em diferentes níveis e áreas. Os córtices
recebem as aferências, recebem também ativação lateral -intercortical- (t
dois) e reenviam a ativação lateralmente e/ou iniciam emergências (t três).
Ativações podem ser elétricas ou químicas, e podem ser excitatórias,
inibitórias, moduladoras. [a ser continuado]

2015-04-17 13:28 GMT-03:00 Rafael Picanço notifications@github.com:

**Comment by cpicanco** [comment]
Não estou seguro, mas para mim faz sentido de que o licenciamento seja anterior ao registro junto ao INPI.

Podemos incluir a lista de todos os autores em um arquivo como parte integrante do software, especificando suas contribuições sempre que possível. O arquivo de licença me parece ser o ideal para isso. Mas nem toda contribuição possuiu registro (o que não a torna uma contribuição menor, ao meu ver), por exemplo, as conversas entre os líderes e professores da EEP com os desenvolvedores que orientaram o seu trabalho de escrita, programação, planejamento e desenvolvimento. Isso faz com que o projeto (o software) seja autoria de todos, mas o registro, o código nesse caso, seja autoria do Drausio  até a versão 4.0.4 e do Drausio e minha nas versões subsequentes. Nesse caso autor é quem escreve, mas lógico, o produto final, o software compilado, deve necessariamente ser autoria de todos. O que você acha??

Eu tenho conhecimento de que o Drausio abdicou da autoria em relação a esse projeto por conta de questões pessoais. Eu conversei com ele por e-mail já há algum tempo por isso afirmo isso, mas eu realmente ficaria feliz se ele aceitasse.
- Drausio Capobianco (principal desenvolvedor e programador)
- Carlos Rafael F. Picanço (segundo programador, planejamento e documentação)
- Paulo R. K. Goulart (planejamento, orientação e documentação)
- Romariz da Silva Barros (planejamento e orientação)
- Ana Leda de Faria (planejamento e orientação)
- Olavo de Faria Galvão (planejamento e orientação)
- Há algum professor de São Carlos, o orientador do Drausio e.g.?
- Estou esquecendo alguém?

Att.
Rafael

**Comment by ofgalvao** [comment]
Sugiro os três que botaram a mão na massa:

O Paulo foi, junto com o de Man o desenvolvedor do Tabajara, que foi o
começo da sobrevivência do software.
- Drausio Capobianco (principal desenvolvedor e programador)
- Carlos Rafael F. Picanço (segundo programador, planejamento e
  documentação)
- Paulo R. K. Goulart (planejamento, orientação e documentação)

Olavo F. Galvão
Prof. Titular Psicol. Experimental, PPGNC, NTPC, UFPA
http://www.ufpa.br/eep/
The brain doesn't think, does nothing mental. The body in its integrity,
not only the brain, sustain the flux of consciousness without being
conscient. During life afferences and efferences make ways respectively
divergent and convergent. In a given instant t zero a set of afferences
demand cortices in different levels and areas. The cortices receive the
aferences, receive also lateral activation -intercortical- (t one) and
re-send the activation laterally and/or start eferences (t two).
Activations may be electrical or chemical, and can be excitatory,

## inibitory, modulatory. [to be continued]

O cérebro não pensa, não faz nada mental. O corpo como um todo, não o
cérebro apenas, sustenta o fluxo da consciência sem ser consciente. Ao
longo da vida, aferências e eferências formam caminhos respectivamente
divergentes e convergentes. Em um dado instante t zero um conjunto de
aferências demanda córtices em diferentes níveis e áreas. Os córtices
recebem as aferências, recebem também ativação lateral -intercortical- (t
dois) e reenviam a ativação lateralmente e/ou iniciam emergências (t três).
Ativações podem ser elétricas ou químicas, e podem ser excitatórias,
inibitórias, moduladoras. [a ser continuado]

2015-04-17 17:14 GMT-03:00 Rafael Picanço notifications@github.com:

**Comment by cpicanco** [comment]
o que você acha @goulartprk ?

**Comment by goulartprk** [comment]
Falta o DeMan na relação de autores. Como o Olavo mencionou, ele foi instrumental para a sobrevida do EAM.

Quanto às questões de licenciamento e registro, não tenho acréscimos nem oposições; tendo a concordar com o que foi dito até aqui.

**Comment by cpicanco** [comment]
@ofgalvao, não entendi muito bem a sua sugestão. Você sugere deixar **apenas** aqueles que "meteram a mão na massa"? 

Por hora, sugiro o seguinte texto como cabeçalho do arquivo de autores, em acordo com o modelo sugerido no site da licença e semelhante ao que tenho usado no _[fork](https://github.com/cpicanco/validation_project)_ mais recente no qual tenho trabalhado no contexto do doutorado (sobre rastreamento de visão). Cliquem ai e dêem uma conferida nos _issues_, tanto os fechados quanto os abertos, eles dão alguma noção do que tenho feito.

Esse _fork_ mais recente talvez se torne a base para um EAM 5, daqui há algum tempo quem sabe, pois já foi migrado para um ambiente de desenvolvimento livre. Ele contém várias melhorias na versão para o linux que podem ser aproveitadas para o windows. Ainda resta testar tudo no mac e reescrever alguns detalhes para tornar o código mais claro (pois eu tenho tido o péssimo hábito de escrever planejando, ao invés de planejar antes de escrever, mas já melhorei bastante, eu acho).

Não estou certo a respeito da data de início do programa; 2007 é a data mais antiga no código cedido pelo Drausio (o arquivo Source.rar no dropbox).

Por favor, se possível revisem o texto a seguir!

Esse seria o nome do arquivo:

> authors-release-note

E a seguir seu conteúdo:

```
EAM - Stimulus Control Application
Copyright (C) 2007-2015 The EAM authors team.

The EAM authors team is formed by:
- Drausio Capobianco (main software developer and former programmer)
- Carlos Rafael F. Picanço (second programmer, planning and documentation)
- Paulo R. K. Goulart (planning, development advisor and documentation)
- Tiago S. Larroudé de Man (planning and documentation)
- Universidade Federal do Pará (physical and institutional support)
- Universidade Federal de São Carlos (physical and institutional support)

We thanks all the authors that made this software happens,
from its early development, passing through its midlife surviving,
until to its current state. 

This file is part of EAM.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

**Comment by ofgalvao** [comment]
Perfeito!

Muito obrigado.

Olavo F. Galvão
Prof. Titular Psicol. Experimental, PPGNC, NTPC, UFPA
http://www.ufpa.br/eep/
The brain doesn't think, does nothing mental. The body in its integrity,
not only the brain, sustain the flux of consciousness without being
conscient. During life afferences and efferences make ways respectively
divergent and convergent. In a given instant t zero a set of afferences
demand cortices in different levels and areas. The cortices receive the
aferences, receive also lateral activation -intercortical- (t one) and
re-send the activation laterally and/or start eferences (t two).
Activations may be electrical or chemical, and can be excitatory,

## inibitory, modulatory. [to be continued]

O cérebro não pensa, não faz nada mental. O corpo como um todo, não o
cérebro apenas, sustenta o fluxo da consciência sem ser consciente. Ao
longo da vida, aferências e eferências formam caminhos respectivamente
divergentes e convergentes. Em um dado instante t zero um conjunto de
aferências demanda córtices em diferentes níveis e áreas. Os córtices
recebem as aferências, recebem também ativação lateral -intercortical- (t
dois) e reenviam a ativação lateralmente e/ou iniciam emergências (t três).
Ativações podem ser elétricas ou químicas, e podem ser excitatórias,
inibitórias, moduladoras. [a ser continuado]

**Comment by cpicanco** [comment]
Por favor, reabram a questão se necessário.
