### ISSUE TITLE
Sobre os grupos do eep-lab

### ISSUE THREAD

**Issue by cpicanco** [eep-lab/eam_docs#3]
O GitHub da EEP possui três grupos (eu criei dois grupos para testar agora, Desenvolvedores e Professores). Mas o que é um grupo? E qual a utilidade deles? Bem, eu não sei o suficiente ainda para responder a essas perguntas e por isso precisamos fazer alguns testes e discutir.

@goulartprk, preciso saber quais os privilégios que você possui agora, pois você está no grupo dos Donos. Eu também estou. O que eu gostaria de saber é se possuímos os mesmo privilégios, mesmo você tendo entrado depois. Podemos marcar um dia para ver isso?

@ofgalvao, você recebeu o convite para entrar como membro do eep-lab?

@tamyresleal, já é membro do grupo Professores. @icarogomes, você recebeu o convite?

@icarogonzaga você recebeu o convite?

@santanaluizhenrique você recebeu o convite?

@ryanespiritosanto você recebeu o convite?

@nicpsico, você recebeu o convite?

Falta ainda alguém? 

Desenvolvedores é apenas um grupo de teste ainda. 

__

**Comment by santanaluizhenrique** [comment]
Recebido.

2015-04-29 23:58 GMT-03:00 Rafael Picanço notifications@github.com:

> O GitHub da EEP possui três grupos (eu criei dois grupos para testar agora
> Desenvolvedores e Professores). Mas o que é um grupo? E qual a utilidade
> deles? Bem, eu não sei o suficiente ainda para responder a essas perguntas
> e por isso precisamos fazer alguns testes e discutir.
> 
> @goulartprk https://github.com/goulartprk, preciso saber quais os
> privilégios que você possui agora, pois você está no grupo dos Donos. Eu
> também estou. O que eu gostaria de saber é se possuímos os mesmo
> privilégios, mesmo você tendo entrado depois. Podemos marcar um dia para
> ver isso?
> 
> @ofgalvao https://github.com/ofgalvao, você recebeu o convite para
> entrar como membro do eep-lab?
> 
> @tamyresleal https://github.com/tamyresleal, já é membro do grupo
> Professores. @icarogomes https://github.com/icarogomes, você recebeu o
> convite?
> 
> @icarogonzaga https://github.com/icarogonzaga você recebeu o convite?
> 
> @santanaluizhenrique https://github.com/santanaluizhenrique você
> recebeu o convite?
> 
> @ryanespiritosanto https://github.com/ryanespiritosanto você recebeu o
> convite?
> 
> Falta ainda alguém?
> 
> Desenvolvedores é apenas um grupo de teste ainda.
> 
> __
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eep-lab/eam_docs/issues/3.

## 

Luiz Henrique Santana

MSc student in Neuroscience and Cognition. Federal University of ABC
http://neuro.ufabc.edu.br, Brazil.

BA in Psychology. Federal University of Pará http://www.ufpa.br/, Brazil.

Yahoo-Mail: santana.luizhenrique@yahoo.com

Google-Mail: santana.lhc@gmail.com.

_Curriculum Vitae (Lattes http://lattes.cnpq.br/7532273136481743)_

_"Parting is all we know of heaven, and all we need of hell." - Emily
Dickinson_

**Comment by ryanespiritosanto** [comment]
Recebido!

Acho que falta a nicole ser adicionada 

Enviado do meu iPhone

**Comment by nicpsico** [comment]
sim!

obrigada.

Em 4 de maio de 2015 17:57, Rafael Picanço notifications@github.com
escreveu:

> O GitHub da EEP possui três grupos (eu criei dois grupos para testar agora
> Desenvolvedores e Professores). Mas o que é um grupo? E qual a utilidade
> deles? Bem, eu não sei o suficiente ainda para responder a essas perguntas
> e por isso precisamos fazer alguns testes e discutir.
> 
> @goulartprk https://github.com/goulartprk, preciso saber quais os
> privilégios que você possui agora, pois você está no grupo dos Donos. Eu
> também estou. O que eu gostaria de saber é se possuímos os mesmo
> privilégios, mesmo você tendo entrado depois. Podemos marcar um dia para
> ver isso?
> 
> @ofgalvao https://github.com/ofgalvao, você recebeu o convite para
> entrar como membro do eep-lab?
> 
> @tamyresleal https://github.com/tamyresleal, já é membro do grupo
> Professores. @icarogomes https://github.com/icarogomes, você recebeu o
> convite?
> 
> @icarogonzaga https://github.com/icarogonzaga você recebeu o convite?
> 
> @santanaluizhenrique https://github.com/santanaluizhenrique você
> recebeu o convite?
> 
> @ryanespiritosanto https://github.com/ryanespiritosanto você recebeu o
> convite?
> 
> @nicpsico https://github.com/nicpsico, você recebeu o convite?
> 
> Falta ainda alguém?
> 
> Desenvolvedores é apenas um grupo de teste ainda.
> 
> __
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eep-lab/eam_docs/issues/3.

## 

_Nicole Lobato_

**Comment by icarogomes** [comment]
Ao tentar rodar sessão no EAM 4.3, no sistema operacional windows 7, obtive a seguinte mensagem de erro: 
![image](https://cloud.githubusercontent.com/assets/11999427/8315143/d5da7e52-19c4-11e5-9bf4-29da8ecf59e7.png)

O Rafael fez o seguinte comentário: 
Mscomm é uma dll. Alguns sistemas exigem que você instale essa dll. O link do dropbox que a Leda, Olavo e Goulart tem acesso contém essa dll e o procedimento de instalação. Uma alternativa é procurar no google.
Eu e o Olavo pegamos a dll Mscomm, no entanto, ela aparece como mscomm [.zip].
Rafael, gostaria de saber agora qual o passo seguinte.

**Comment by cpicanco** [comment]
O nome do arquivo deve ter sido alterado para evitar problemas ao enviá-lo
por e-mail. Estou às cegas nesse momento, isto é, não tenho condições de
dar alguns detalhes importantes, mas os passos a seguir merecem ser
testados.

- Renomeie o arquivo para `mscomm.zip`

- extraia a dll de dentro desse arquivo para a mesma pasta do executável do
EAM;

- teste para ver se o problema foi resolvido, caso não, siga os passos
seguinte;

- procure o procedimento de instalação da dll em um arquivo de texto
chamado LEIA-ME, ou algo do tipo, na pasta do dropbox;

- siga os passos de instalação...

**NOTA**

Essa dll é proprietária e apenas disponível em alguns sistemas, se eu não
estiver enganado, sistemas que possuem o VBA (Virtual Basic for
Applications). O procedimento envolve a alteração de uma chave no registro
do windows com o objetivo de autorizar o uso da dll mesmo sem o VBA. Nada
complicado, esta chave deve estar na pasta do dropbox também e basta dar
dois cliques...

Uma boa idea é buscar uma maneira de implementar a comunicação com a
interface Kaleb sem essa dll. Eu vou investigar isso.

**Comment by cpicanco** [comment]
Ahhh... Eu gostaria que você criasse um novo ISSUE... Clique no botão verde
NEW ISSUE que deve estar em algum lugar por ai... Rsrsrs

**Comment by cpicanco** [comment]
Olá @eep-lab/professores , por favor, sempre que for necessário criem um novo ISSUE para qualquer dúvida, questão, problema ou tópico novo que surgir. Basta clicar no botão verde:
![screenshot - 06292015 - 11 28 28 am](https://cloud.githubusercontent.com/assets/6511849/8410099/7c752f6e-1e52-11e5-8f53-9ff1892a9849.png)

**Comment by santanaluizhenrique** [comment]
Olá,

À quem interessar, segue a indicação e uma plataforma online de softwares e
ferramentas de análise em código aberto e distribuição livre, especializada
em análise de tarefas comportamentais e registro e análises
eletrofisiológicas.

Montagem, Assistência Técnica e serviços oferecidos por empresa nacional
dirigida por colegas pesquisadores em Neurociências.

Recomendo conferir o conteúdo.

Um abraço,

---------- Forwarded message ----------
From: Eliezyer Fermino de Oliveira <fermino.bioeng@gmail.com>
Date: 2017-04-04 14:22 GMT-03:00
Subject: Carta para divulgação e avaliação de interesse da comunidade sobre
o Open Ephys
To: Luiz Henrique Santana <santana.lhc@gmail.com>, Estela Braga <
nepomoceno@hotmail.com>


Olá,

Peço encaredicamente que divulguem a carta e o orçamento anexados aos
possíveis interessados em adquirir um sistema de registro eletrofisiológico
de baixo custo e alta qualidade para seus laboratórios.

Abraços,
Eliezyer



-- 

Luiz Henrique Santana

Ph.D. student in Experimental Psychology. University of São Paulo
<http://www.ip.usp.br/portal/index.php?option=com_content&id=1636:psicologia-experimental&Itemid=68&lang=pt>,
Brazil.

M.Sc, Neuroscience and Cognition. Federal University of ABC
<http://neuro.ufabc.edu.br/>, Brazil.

BSc in Psychology. Federal University of Pará <http://www.ufpa.br/>, Brazil.

Google-Mail: santana.lhc@gmail.com.

*Curriculum Vitae (Lattes <http://lattes.cnpq.br/7532273136481743>)*


*"Physics investigates the essential nature of the world, and biology
describes a local bump. Psychology, human psychology, describes a bump on
the bump.".**Willard Van Orman Quine. Theories and Things (1981).*
