### ISSUE TITLE
Problema no contador

### ISSUE THREAD

**Issue by ryanespiritosanto** [eep-lab/eam_docs#5]
Oi Rafa,

Estou usando o EAM para fazer minha pesquisa do mestrado.

Baixei essa versão 4.3 que está disponível aqui no GitHub

Em anexo está a sessão que programei

Fiz uma sessão de discriminação condicional. Usei o contador como consequência para erros e acertos. Abri a janela auxiliar e o programa está registrando erros e acertos como programado, mas o contador que aparece durante o IET só mostra o número 1, independente de acerto ou erro.

Como faço pro contador ir acumulando acertos e não aparecer nenhuma pontuação para erros?

Abraços
[sessão 05 teste.txt](https://github.com/eep-lab/eam_docs/files/46106/sessao.05.teste.txt)

**Comment by cpicanco** [comment]
Vou conferir isso @ryanespiritosanto ,

**Comment by cpicanco** [comment]
https://github.com/eep-lab/eam_docs/releases/tag/4.3

**Comment by cpicanco** [comment]
Testa ai @ryanespiritosanto . Se funcionar basta fechar esse problema (close issue).

**Comment by cpicanco** [comment]
E sim, eu recebo tudo por e-mail. Se eu não estiver no computador pode demorar um pouco para eu responder. (24h)

**Comment by ryanespiritosanto** [comment]
Valeu Rafa! Funcionou perfeitamente!

Uma sugestão é ter uma opção para contagem global com todos os blocos e uma contagem global. Alguns procedimentos podem precisar ter uma contagem por blocos

Abraços
