### ISSUE TITLE
Relatório de Dados

### ISSUE THREAD

**Issue by ryanespiritosanto** [eep-lab/eam_docs#6]
Como é uma questão diferente da anterior, abri um novo issue

Olhei o relatório de dados e percebi que não existe uma contagem total de acertos por blocos. Não sei se tem alguma opção para isso que não programei ou o programa não possui essa possibilidade.

Outra possibilidade é que minha sessão foi programada sem critério de acertos para avançar no bloco, apenas o número de tentativas programadas. Isso afeta o relatório final de dados nessa questão de contagem total de acertos?

Abraços

**Comment by cpicanco** [comment]
Não estou seguro, talvez eu não tenha entendido muito bem o que você está pedindo. 

A contagem de acertos e erros atualmente fica a cargo do professor, pois erros e acertos de cada tentativa são definidos nas configurações (por meio dos valores HIT, MISS e NONE da chave RES= nos estímulos). Lembre-se que também é possível definir o que é uma tentativa por meio da configuração "Virtual Trial". 

Os contadores internos do EAM são sensíveis apenas a esses parâmetros [por exemplo](https://github.com/eep-lab/eam/blob/master/Units/uCounterManager.pas). Os relatórios não reportam todos os valores dos contadores a todo momento( por uma questão de economia de espaço), mas até aonde o meu pensamento vai todas as contagens podem ser deduzidas por meio dos dados brutos.

Há alguma informação que está faltando no relatório?

**Comment by ryanespiritosanto** [comment]
Entendi Rafa

É porque entrei em contato com alguns programas que já faziam a contagem dos acertos e erros por bloco e pensei que o EAM tinha essa funcionalidade também. 

Também no meu procedimento de SPAN, por causa da entrada USB, aparecia 1 para acerto e 0 para  erro, o que facilitava a contagem do total de acertos. Pensei que tinha algo parecido para tarefas de discriminação condicional. 

Mas tranquilo, o mais importante é que o os acertos e erros estão no relatório e dá para fazer a contagem geral.

Abraços

**Comment by cpicanco** [comment]
Existem pelo menos três maneiras de contar os acertos e erros (ou nones).

1) Se as consequências estão associadas aos acertos, ler os valores da coluna 'Disp.   ' ou 'UDsp.   ' do relatório.
2) Definir mensagens diferencias para o estímulo correto/errado/none.
3) Se sempre o primeiro estímulo for o correto (C1), o que o EAM faz por padrão, ler os valores correspondentes na coluna 'Res.Frq.

**Comment by cpicanco** [comment]
Se você tiver alguma dúvida sobre como automatizar isso, me manda um relatório que eu te mostro como fazer. :smile:
