### ISSUE TITLE
Aleatorizar ordem das tentativas 

### ISSUE THREAD

**Issue by Pcsoares** [eep-lab/eam_docs#8]
Na opção "Aleatorizar ordem das tentativas", quando clico nessa opção as tentativas são aleatorizadas, porém quando clico em "Aplicar", elas voltam à ordem numérica sequencial. Tentei muda-las manualmente mas o erro persiste.

**Comment by cpicanco** [comment]
Recordo que há um erro deste tipo. Entretanto, ao clicar em aplicar a numeração das tentativas muda, mas a ordem delas se mantém. Você pode confirmar se a ordem das tentativas mudou de fato a despeito dessa numeração?

**Comment by Pcsoares** [comment]
Sim, mudou! Obrigada
