### ISSUE TITLE
Evitar arquivos PDF no repositório.

### ISSUE THREAD

**Issue by cpicanco** [eep-lab/eam_docs#9]
@eep-lab/professores gostaria de propor algo ao grupo.

Com o objetivo de facilitar a edição dos arquivos de documentação por qualquer um,  é necessário evitar arquivos PDF no repositório. Gostaria que @figueiredorad ou alguém do grupo convertesse o arquivo pdf para um arquivo .markdown: http://guides.github.com/features/mastering-markdown/

Como fazer isso?

1. Suba todos os arquivos de figuras para a seguinte pasta (eu acabei de criar ela): https://github.com/eep-lab/eam_docs/tree/master/passo_a_passo/criar_nova_sessao_no_eam_43

2. Copie todo o texto do arquivo fonte, não do pdf, do arquivo fonte (suspeito que seja um doc) [desse pdf](https://github.com/eep-lab/eam_docs/blob/f43edd1b09c0a2bbc1eb3b2342b09d7c3b6f6037/Passo%20a%20passo%20para%20criar%20uma%20nova%20sess%C3%A3o%20no%20EAM%204.pdf) para o arquivo README.md localizado dentro da pasta https://github.com/eep-lab/eam_docs/tree/master/passo_a_passo/criar_nova_sessao_no_eam_43

3. Basta, então, linkar cada arquivo de imagem usando a seguinte sintaxe (em markdown):

       ![Breve descrição da imagem](https://octodex.github.com/images/yaktocat.png)

![Breve descrição da imagem](https://octodex.github.com/images/yaktocat.png)

OBS.: Substitua o link https://octodex.github.com/images/yaktocat.png pelo caminho do arquivo da imagem naquela pasta. Qualquer dúvida consulte o link: http://guides.github.com/features/mastering-markdown/

**Comment by cpicanco** [comment]
Como são vários arquivos, seria bom usar o git para adicioná-los todos de uma vez. É muito simples usar o git por meio do Github Desktop no windows.

https://desktop.github.com/

Basta:

1. instalar o Github Desktop;
2. clonar o repositório da eep_docs usando este link https://github.com/eep-lab/eam_docs.git
3. copiar e colar as figuras para aquela pasta no repositório clonado usando o Windows Explorer
4. o GitHub Desktop, então, irá reconhecer as figuras, todas elas deverão estar selecionadas e basta clicar em COMMIT (botão no lado inferior esquerdo, selecione a aba CHANGES no topo se necessário, para adicionar as mudanças no repositório local clonado
5. basta clicar no botão SYNCH (no canto superior direito) para enviar essas mudanças para o repositório remoto (on line)

**Comment by ofgalvao** [comment]
O Willian está trabalhando para fazer o documento compatível com as suas instruções.

**Comment by cpicanco** [comment]
@WillianSantana, qualquer dúvida pode perguntar por aqui!

**Comment by cpicanco** [comment]
@ofgalvao vi que você tentou adicionar o link. Fiz um exemplo, você pode conferir aqui:

https://github.com/eep-lab/eam_docs/blob/master/passo_a_passo/criar_nova_sessao_no_eam_43/README.md

A sintaxe é bem simples:

> `![Figura 1](Figura_01.jpg)`

Você pode conferir o arquivo de texto aqui:

https://raw.githubusercontent.com/eep-lab/eam_docs/master/passo_a_passo/criar_nova_sessao_no_eam_43/README.md

**Comment by WillianSantana** [comment]
Rafael, foi eu que modifiquei o GitHub. Estava tentando seguir aqueles passos que você mandou, porém ficou incompleto o serviço porque o computador que estava usando precisou ser usado por outra pessoa no momento.


Vou seguir essas orientações que você deu.


Obrigado


Willian Ferreira


________________________________
De: Rafael Picanço <notifications@github.com>
Enviado: terça-feira, 4 de abril de 2017 17:57:08
Para: eep-lab/eam_docs
Cc: WillianSantana; Mention
Assunto: Re: [eep-lab/eam_docs] Evitar arquivos PDF no repositório. (#9)


@ofgalvao<https://github.com/ofgalvao> vi que você tentou adicionar o link. Fiz um exemplo, você pode conferir aqui:

https://github.com/eep-lab/eam_docs/blob/master/passo_a_passo/criar_nova_sessao_no_eam_43/README.md

A sintaxe é bem simples:

[Figura 1]<Figura_01.jpg>

Você pode conferir o arquivo de texto aqui:

https://raw.githubusercontent.com/eep-lab/eam_docs/master/passo_a_passo/criar_nova_sessao_no_eam_43/README.md

**Comment by ofgalvao** [comment]
estou tentando achar como editar... sozinho nano estou conseguindo...

Olavo F. Galvão
Professor Titular, PPG Neurociências e Comportamento, NTPC, UFPA
www.ppgnc.propesp.ufpa.br; www.ufpa.br/eep/
... how many times can a man turn his head
And pretend that he just doesn't see?
The answer, my friend, is blowin' in the wind
The answer is blowin' in the wind... Bob Dylan
<https://www.google.com.br/search?biw=1222&bih=689&site=webhp&q=Bob+Dylan&stick=H4sIAAAAAAAAAONgVuLSz9U3MCwryksuBgBiqtVvDgAAAA&sa=X&ved=0ahUKEwiP9K-J3ZXRAhWFW5AKHaaUD7wQMQghMAA>

2017-04-04 18:04 GMT-03:00 WillianSantana <notifications@github.com>:

**Comment by WillianSantana** [comment]
Já está editado e pronto para uso.

https://github.com/eep-lab/eam_docs/blob/master/passo_a_passo/criar_nova_sessao_no_eam_43/README.md

[https://avatars0.githubusercontent.com/u/11935747?v=3&s=400]<https://github.com/eep-lab/eam_docs/blob/master/passo_a_passo/criar_nova_sessao_no_eam_43/README.md>

eep-lab/eam_docs<https://github.com/eep-lab/eam_docs/blob/master/passo_a_passo/criar_nova_sessao_no_eam_43/README.md>
github.com
eam_docs - Documentação do EAM





Willian Ferreira



________________________________
De: Olavo Galvao <notifications@github.com>
Enviado: terça-feira, 4 de abril de 2017 19:06:19
Para: eep-lab/eam_docs
Cc: WillianSantana; Mention
Assunto: Re: [eep-lab/eam_docs] Evitar arquivos PDF no repositório. (#9)

estou tentando achar como editar... sozinho nano estou conseguindo...

Olavo F. Galvão
Professor Titular, PPG Neurociências e Comportamento, NTPC, UFPA
www.ppgnc.propesp.ufpa.br; www.ufpa.br/eep/
... how many times can a man turn his head
And pretend that he just doesn't see?
The answer, my friend, is blowin' in the wind
The answer is blowin' in the wind... Bob Dylan
<https://www.google.com.br/search?biw=1222&bih=689&site=webhp&q=Bob+Dylan&stick=H4sIAAAAAAAAAONgVuLSz9U3MCwryksuBgBiqtVvDgAAAA&sa=X&ved=0ahUKEwiP9K-J3ZXRAhWFW5AKHaaUD7wQMQghMAA>

2017-04-04 18:04 GMT-03:00 WillianSantana <notifications@github.com>:

**Comment by cpicanco** [comment]
Muito Bom! @WillianSantana
